package com.asw.corba.ex2.BillingServiceModule;


/**
* com/asw/corba/ex2/BillingServiceModule/BillingServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from com/asw/corba/ex2/BillingService.idl
* 16 Èþëü 2006 ã. 15:01:11 MSD
*/

public interface BillingServiceOperations 
{
  com.asw.corba.ex2.BillingServiceModule.Card getCard (String card);
  com.asw.corba.ex2.BillingServiceModule.Card addNewCard (String personName, String card);
} // interface BillingServiceOperations
