package com.asw.corba.ex2.BillingServiceModule;


/**
* com/asw/corba/ex2/BillingServiceModule/BillingService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from com/asw/corba/ex2/BillingService.idl
* 16 Èþëü 2006 ã. 15:01:11 MSD
*/

public interface BillingService extends BillingServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BillingService
