package com.asw.corba.ex2.BillingServiceModule;


/**
* com/asw/corba/ex2/BillingServiceModule/CardHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from com/asw/corba/ex2/BillingService.idl
* 16 Èþëü 2006 ã. 15:01:11 MSD
*/

abstract public class CardHelper
{
  private static String  _id = "IDL:BillingServiceModule/Card:1.0";

  public static void insert (org.omg.CORBA.Any a, com.asw.corba.ex2.BillingServiceModule.Card that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.asw.corba.ex2.BillingServiceModule.Card extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (com.asw.corba.ex2.BillingServiceModule.CardHelper.id (), "Card");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.asw.corba.ex2.BillingServiceModule.Card read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CardStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.asw.corba.ex2.BillingServiceModule.Card value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static com.asw.corba.ex2.BillingServiceModule.Card narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof com.asw.corba.ex2.BillingServiceModule.Card)
      return (com.asw.corba.ex2.BillingServiceModule.Card)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      com.asw.corba.ex2.BillingServiceModule._CardStub stub = new com.asw.corba.ex2.BillingServiceModule._CardStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
