package com.asw.corba.ex2.BillingServiceModule;

/**
* com/asw/corba/ex2/BillingServiceModule/CardHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from com/asw/corba/ex2/BillingService.idl
* 16 Èþëü 2006 ã. 15:01:11 MSD
*/

public final class CardHolder implements org.omg.CORBA.portable.Streamable
{
  public com.asw.corba.ex2.BillingServiceModule.Card value = null;

  public CardHolder ()
  {
  }

  public CardHolder (com.asw.corba.ex2.BillingServiceModule.Card initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.asw.corba.ex2.BillingServiceModule.CardHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.asw.corba.ex2.BillingServiceModule.CardHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.asw.corba.ex2.BillingServiceModule.CardHelper.type ();
  }

}
