package com.asw.corba.ex1.BillingServiceModule;


/**
* com/asw/corba/ex1/BillingServiceModule/BillingService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from com/asw/corba/ex1/BillingService.idl
* 16 Èþëü 2006 ã. 14:12:21 MSD
*/

public interface BillingService extends BillingServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BillingService
